# Generated by Django 2.1.4 on 2018-12-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silk', '0006_fix_request_prof_file_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='user',
            field=models.TextField(default=None, null=True),
        ),
    ]
