# Generated by Django 2.1.4 on 2018-12-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('silk', '0007_request_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='platform',
            field=models.TextField(default=None, null=True),
        ),
    ]
